databases:
  - name: appscholar-db
    plan: free
    region: oregon
    databaseName: scholar_db
    user: appscholar_user

services:
  - type: web
    runtime: docker
    name: appscholar-backend
    region: oregon
    plan: starter
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    preDeployCommand: npm --prefix backend migrate:deploy && npm --prefix backend run seed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: appscholar-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
