/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/grades`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/students`; params?: Router.UnknownInputParams; } | { pathname: `/teachers`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/contexts/auth-context`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-auth`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-form`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `/grades`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/students`; params?: Router.UnknownOutputParams; } | { pathname: `/teachers`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/types/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/contexts/auth-context`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/use-auth`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/use-color-scheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/use-form`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/use-theme-color`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/courses${`?${string}` | `#${string}` | ''}` | `/grades${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/students${`?${string}` | `#${string}` | ''}` | `/teachers${`?${string}` | `#${string}` | ''}` | `/../src/types/index${`?${string}` | `#${string}` | ''}` | `/../src/constants/theme${`?${string}` | `#${string}` | ''}` | `/../src/contexts/auth-context${`?${string}` | `#${string}` | ''}` | `/../src/hooks/use-auth${`?${string}` | `#${string}` | ''}` | `/../src/hooks/use-color-scheme.web${`?${string}` | `#${string}` | ''}` | `/../src/hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../src/hooks/use-form${`?${string}` | `#${string}` | ''}` | `/../src/hooks/use-theme-color${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/grades`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/students`; params?: Router.UnknownInputParams; } | { pathname: `/teachers`; params?: Router.UnknownInputParams; } | { pathname: `/../src/types/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/constants/theme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/contexts/auth-context`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-auth`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-color-scheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-form`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/use-theme-color`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
